import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, Target, Zap, BarChart3, Globe2, ShieldCheck, Leaf, AlertCircle, TrendingUp, ThermometerSun } from 'lucide-react';
import { Link } from 'react-router-dom';

function Hero({ onStart }: { onStart: () => void }) {
  return (
    <section className="relative flex flex-col items-center justify-center px-6 min-h-[85vh]">
      <div className="relative z-10 text-center max-w-5xl mx-auto flex flex-col items-center justify-center w-full gap-8">
        
        <motion.p
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="text-white/80 text-[10px] md:text-[11px] font-medium tracking-[0.2em] uppercase mb-4"
        >
          THE ENVIRONMENTAL IMPACT TRACKER
        </motion.p>
        
        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
          className="text-4xl md:text-[64px] font-medium tracking-[-0.01em] leading-[1.1] bg-gradient-to-b from-white via-white/95 to-white/70 bg-clip-text text-transparent max-w-4xl"
          style={{ fontFamily: "'Instrument Serif', serif" }}
        >
          Measure, Understand, and Reduce <br className="hidden md:block" /> Your Carbon Footprint
        </motion.h1>

        <motion.p 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="text-white/70 text-lg max-w-[600px] leading-relaxed"
        >
          A single platform to track your food, transport, and energy in seconds, helping you reverse global climate change.
        </motion.p>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4 }}
          className="mt-6 flex flex-col sm:flex-row gap-4 justify-center items-center"
        >
          <button
            onClick={onStart}
            className="glass px-10 py-4 text-[15px] flex items-center gap-2 rounded-full font-semibold"
          >
            Start Your Journey <ArrowRight className="w-5 h-5" />
          </button>
        </motion.div>
      </div>
    </section>
  );
}

function EducationalSections() {
  const fadeUp = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } }
  };

  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.15 } }
  };

  return (
    <section className="relative z-10 py-16">
      <div className="max-w-5xl mx-auto px-6">
        <motion.div 
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {/* Definition */}
          <motion.div variants={fadeUp} className="glass p-8 col-span-1 lg:col-span-2 flex flex-col justify-center">
            <div className="flex items-center gap-3 mb-4 text-white">
              <Leaf size={24} className="text-green-400" />
              <h3 className="font-semibold text-xl">What is a Carbon Footprint?</h3>
            </div>
            <p className="text-white/80 leading-relaxed">
              A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Everything from the electricity that powers our homes to the food we eat contributes to this invisible environmental toll.
            </p>
          </motion.div>

          {/* Why it Matters */}
          <motion.div variants={fadeUp} className="glass p-8 flex flex-col justify-center">
            <div className="flex items-center gap-3 mb-4 text-white">
              <AlertCircle size={24} className="text-red-400" />
              <h3 className="font-semibold text-xl">Why It Matters</h3>
            </div>
            <p className="text-white/80 leading-relaxed text-sm">
              Rising CO₂ levels trap heat in the atmosphere, driving extreme weather, rising sea levels, and ecosystem collapse. Reducing individual footprints is critical.
            </p>
          </motion.div>

          {/* Global Stats */}
          <motion.div variants={fadeUp} className="glass p-8 col-span-1 md:col-span-2 lg:col-span-3 flex flex-col sm:flex-row gap-8 items-center justify-between">
            <div className="flex-1">
              <h3 className="font-semibold text-xl text-white mb-2">The Global Reality</h3>
              <p className="text-white/70 text-sm">We must drastically reduce emissions to limit global warming to 1.5°C above pre-industrial levels.</p>
            </div>
            <div className="flex gap-4 w-full sm:w-auto">
              <div className="flex-1 sm:flex-none glass p-4 text-center">
                <ThermometerSun size={24} className="text-orange-400 mx-auto mb-2" />
                <div className="font-bold text-2xl text-white">+1.1°C</div>
                <div className="text-xs text-white/50 uppercase tracking-widest mt-1">Current Warming</div>
              </div>
              <div className="flex-1 sm:flex-none glass p-4 text-center">
                <TrendingUp size={24} className="text-red-400 mx-auto mb-2" />
                <div className="font-bold text-2xl text-white">4.7t</div>
                <div className="text-xs text-white/50 uppercase tracking-widest mt-1">Global Avg / Person</div>
              </div>
            </div>
          </motion.div>

        </motion.div>
      </div>
    </section>
  );
}

function ExtendedSections() {
  const fadeUp = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] } }
  };

  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.15 } }
  };

  return (
    <div className="relative z-10 pb-32">
      {/* How It Works */}
      <section id="how-it-works" className="py-24 sm:py-32">
        <div className="max-w-5xl mx-auto px-6">
          <motion.div 
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className="text-center mb-16"
          >
            <motion.h2 variants={fadeUp} style={{ fontFamily: "'Instrument Serif', serif" }} className="text-4xl sm:text-5xl font-medium text-white mb-4">How Carbonly Works</motion.h2>
            <motion.p variants={fadeUp} className="text-white/70 text-lg">Three simple steps to transform your environmental impact.</motion.p>
          </motion.div>

          <motion.div 
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className="grid md:grid-cols-3 gap-6"
          >
            {[
              { icon: <Target />, title: "1. Set Baseline", desc: "Answer 3 quick questions to establish your localized carbon emissions baseline." },
              { icon: <Zap />, title: "2. Fast Daily Logs", desc: "Log your daily food, transit, and energy usage in under 20 seconds." },
              { icon: <BarChart3 />, title: "3. Track & Reduce", desc: "View beautiful analytics and get AI-driven nudges to lower your footprint." }
            ].map((step, i) => (
              <motion.div key={i} variants={fadeUp} className="glass glass-hover p-8">
                <div className="w-12 h-12 glass flex items-center justify-center text-white mb-6 rounded-full">
                  {step.icon}
                </div>
                <h3 className="font-semibold text-lg mb-3 text-white">{step.title}</h3>
                <p className="text-white/70 text-sm leading-relaxed">{step.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24">
        <div className="max-w-5xl mx-auto px-6">
          <motion.div 
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className="glass p-10 sm:p-16 flex flex-col md:flex-row gap-16 items-center"
          >
            <div className="flex-1">
              <motion.h2 variants={fadeUp} style={{ fontFamily: "'Instrument Serif', serif" }} className="text-4xl sm:text-5xl font-medium text-white mb-6">
                Engineered for speed and accuracy.
              </motion.h2>
              <motion.p variants={fadeUp} className="text-white/70 text-lg mb-8 leading-relaxed">
                Carbon accounting shouldn't be a chore. We built a system that learns your habits, requiring only absolute minimal input.
              </motion.p>
              
              <div className="flex flex-col gap-6">
                {[
                  { icon: <Globe2 size={18} />, text: "Localized IPCC & CEA Emission Factors" },
                  { icon: <ShieldCheck size={18} />, text: "Privacy-First Local GPS Processing" },
                  { icon: <Leaf size={18} />, text: "Dynamic AI Contextual Nudges" }
                ].map((feature, i) => (
                  <motion.div key={i} variants={fadeUp} className="flex items-center gap-4 text-white font-medium">
                    <div className="w-8 h-8 glass flex items-center justify-center text-white/90 rounded-full">
                      {feature.icon}
                    </div>
                    {feature.text}
                  </motion.div>
                ))}
              </div>
            </div>
            
            <motion.div variants={fadeUp} className="flex-1 w-full flex items-center justify-center">
              <div className="w-full max-w-[320px] glass">
                <div className="p-4 border-b border-white/10 flex justify-between items-center bg-white/5">
                  <div className="w-16 h-3 bg-white/20 rounded-full"></div>
                  <div className="w-6 h-6 bg-white/20 rounded-full"></div>
                </div>
                <div className="p-6 flex flex-col gap-4">
                  <div className="w-24 h-24 rounded-full border-[4px] border-white/10 mx-auto relative mb-2">
                    <div className="absolute inset-0 border-[4px] border-white/60 rounded-full border-t-transparent border-r-transparent transform -rotate-45"></div>
                  </div>
                  <div className="w-full h-10 bg-white/10 rounded-xl"></div>
                  <div className="w-full h-10 bg-white/10 rounded-xl"></div>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}

export default function LandingPage({ onStart }: { onStart: () => void }) {
  return (
    <>
      <Hero onStart={onStart} />
      <EducationalSections />
      <ExtendedSections />
    </>
  );
}
